import { eventFlags, resolveFlag } from '../shared/event-flags';
import { DEFAULT_SETTINGS, cloneSettings, normalizeSettings, type CeremonySettings, type CeremonySlot, type ClientMessage, type ServerMessage } from '../shared/types';

const STORAGE_KEY = 'flag-ceremony.settings.v4';
const PRESETS_KEY = 'flag-ceremony.presets.v1';
const DEFAULT_PRESET_NAME = 'Default';
const MAX_SLOTS = 12;
const MIN_SLOTS = 1;
interface ClothSettings { selfCollision: boolean; collisionThickness: number; collisionIterations: 1 | 2; }
interface FlagMaterialSettings { gloss: number; metalness: number; clearcoat: number; clearcoatGloss: number; }
interface UiSettingsPayload extends CeremonySettings { cloth: ClothSettings; flagMaterial: FlagMaterialSettings; }
const DEFAULT_CLOTH: ClothSettings = { selfCollision: true, collisionThickness: .2, collisionIterations: 2 };
const DEFAULT_FLAG_MATERIAL: FlagMaterialSettings = { gloss: .4, metalness: .5, clearcoat: 0, clearcoatGloss: 0 };
const $ = <T extends HTMLElement>(id: string): T => { const element = document.getElementById(id); if (!element) throw new Error(`Missing control element: #${id}`); return element as T; };
const escape = (value: string): string => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const countriesSorted = eventFlags.filter((flag): flag is typeof flag & { code: string } => flag.code !== null);
const countryMap = new Map(countriesSorted.map((country) => [country.code, country]));
let settings: CeremonySettings = cloneSettings(DEFAULT_SETTINGS);
let cloth: ClothSettings = { ...DEFAULT_CLOTH };
let flagMaterial: FlagMaterialSettings = { ...DEFAULT_FLAG_MATERIAL };
let socket: WebSocket | null = null;
let reconnectTimer: number | undefined;
let feedbackTimer: number | undefined;
let applyingRemote = false;
const debounceTimers = new Map<string, number>();
const hadAutosave = localStorage.getItem(STORAGE_KEY) !== null;
let autosaveBootstrapSent = false;
const slotsList = $<HTMLDivElement>('slots-list'); const feedback = $<HTMLDivElement>('control-feedback'); const status = $<HTMLElement>('connection-status'); const presetName = $<HTMLInputElement>('preset-name'); const presetList = $<HTMLSelectElement>('preset-list'); const importInput = $<HTMLInputElement>('import-file'); const backgroundInput = $<HTMLInputElement>('background-file'); const backgroundName = $<HTMLSpanElement>('background-file-name'); const countryOptions = $<HTMLDataListElement>('country-options'); const flagInput = $<HTMLInputElement>('flag-file'); const flagName = $<HTMLInputElement>('flag-name'); const flagFileName = $<HTMLSpanElement>('flag-file-name');

arrangeDashboard(); populateCountryOptions(); loadAutosave(); renderAll(); wireEvents(); connect();
function arrangeDashboard(): void {
  const action = document.querySelector<HTMLElement>('.action-strip');
  const dashboard = document.querySelector<HTMLElement>('.dashboard-grid');
  const preview = document.querySelector<HTMLElement>('.preview-panel');
  const flags = document.querySelector<HTMLElement>('.flags-panel');
  const wind = document.querySelector<HTMLElement>('.wind-panel');
  const background = document.querySelector<HTMLElement>('.background-panel');
  const poles = document.querySelector<HTMLElement>('.poles-panel');
  const clothPanel = document.querySelector<HTMLElement>('.cloth-panel');
  const presets = document.querySelector<HTMLElement>('.presets-panel');
  const geometryControls = flags?.querySelector<HTMLElement>(':scope > .control-grid');
  const customUpload = flags?.querySelector<HTMLElement>(':scope > .custom-flags');
  const customList = document.getElementById('custom-flags-list');
  if (!action || !dashboard || !preview || !flags || !wind || !background || !poles || !clothPanel || !presets || !geometryControls || !customUpload || !customList) return;
  const workspace = document.createElement('div');
  workspace.className = 'workspace-grid';
  const columns = Array.from({ length: 4 }, () => { const column = document.createElement('div'); column.className = 'workspace-column'; workspace.appendChild(column); return column; });
  const geometry = document.createElement('section');
  geometry.className = 'control-section dashboard-panel geometry-panel';
  geometry.innerHTML = '<div class="section-title"><div><h2>Flag geometry</h2><span class="section-help">Spacing, dimensions and source media.</span></div></div>';
  geometry.append(geometryControls, customUpload, customList);
  columns[0].append(preview, poles);
  columns[1].append(flags, clothPanel);
  columns[2].append(geometry, presets);
  columns[3].append(wind, background);
  action.insertAdjacentElement('afterend', workspace);
  dashboard.remove();
}
function populateCountryOptions(): void { countryOptions.innerHTML = countriesSorted.map(({ code, name }) => `<option value="${escape(code)} — ${escape(name)}"></option>`).join(''); }
function countryName(code: string): string { return countryMap.get(code)?.name ?? code; }
function renderAll(): void { renderSlots(); renderCustomFlags(); syncInputs(); syncBackground(); renderPresetList(); }
function renderSlots(): void {
  slotsList.innerHTML = settings.slots.map((slot, index) => {
    const code = slot.countryCode.toUpperCase();
    const custom = settings.customFlags.find((flag) => flag.id === slot.flagId);
    const builtIn = eventFlags.find((flag) => flag.id === slot.flagId);
    const resolved = resolveFlag(slot, settings.customFlags);
    const selected = custom?.id ?? builtIn?.id ?? code;
    const current = custom || builtIn ? resolved.name : `${code} — ${countryName(code)}`;
    const legacy = !custom && !builtIn && !countryMap.has(code) ? `<option value="${escape(code)}" selected>${escape(code)} — ${escape(countryName(code))}</option>` : '';
    const options = legacy + eventFlags.map((flag) => {
      const value = flag.code ?? flag.id;
      const label = flag.code ? `${flag.code} — ${flag.name}` : flag.name;
      return `<option value="${escape(value)}" ${selected === value || builtIn?.id === flag.id ? 'selected' : ''} ${!flag.imageUrl ? 'disabled' : ''}>${escape(label)}${!flag.imageUrl ? ' (image not supplied)' : ''}</option>`;
    }).join('') + settings.customFlags.map((flag) => `<option value="${escape(flag.id)}" ${custom?.id === flag.id ? 'selected' : ''}>${escape(flag.name)}</option>`).join('');
    return `<article class="slot-card"><div class="slot-card-header"><div class="slot-number" aria-hidden="true">${String(index + 1).padStart(2, '0')}</div><div><h3>Pole ${index + 1}</h3><p class="slot-country-caption">${escape(current)}</p></div></div><div class="slot-card-fields"><label class="field"><span class="field-label">Rank</span><select data-slot-field="rank" data-slot-id="${escape(slot.id)}"><option value="1" ${slot.rank === 1 ? 'selected' : ''}>1 · Gold</option><option value="2" ${slot.rank === 2 ? 'selected' : ''}>2 · Silver</option><option value="3" ${slot.rank === 3 ? 'selected' : ''}>3 · Bronze</option></select></label><label class="field"><span class="field-label">Flag</span><div class="country-input-wrap"><img class="country-flag-thumb" ${resolved.imageUrl ? `src="${escape(resolved.imageUrl)}"` : 'hidden'} alt="${escape(current)}" onerror="this.hidden=true"><select data-slot-field="countryCode" data-slot-id="${escape(slot.id)}">${options}</select></div></label><label class="field"><span class="field-label">X offset <span class="field-unit">m</span></span><input type="number" min="-30" max="30" step=".1" value="${slot.xOffset}" data-slot-field="xOffset" data-slot-id="${escape(slot.id)}"></label></div><button class="slot-delete" type="button" data-action="remove-slot" data-slot-id="${escape(slot.id)}" aria-label="Remove pole ${index + 1}" title="Remove pole" ${settings.slots.length <= MIN_SLOTS ? 'disabled' : ''}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8l1 2h4v2H3V5h4l1-2Zm-2 6h12l-1 12H7L6 9Zm4 2v7h2v-7h-2Zm4 0v7h2v-7h-2Z"/></svg></button></article>`;
  }).join('');
}
function renderCustomFlags(): void { const list = document.getElementById('custom-flags-list'); if (!list) return; list.innerHTML = settings.customFlags.map((flag) => `<div class="custom-flag-row"><img src="${escape(flag.imageUrl)}" alt=""><input value="${escape(flag.name)}" data-flag-name="${escape(flag.id)}"><label class="button button-quiet file-button">Replace image<input type="file" accept="image/png,image/jpeg,image/webp" data-flag-replace="${escape(flag.id)}"></label><button class="button button-quiet" data-action="remove-flag" data-flag-id="${escape(flag.id)}">Remove</button></div>`).join(''); }
function syncInputs(): void { const values: Record<string, string | number | boolean> = { hoistDuration: settings.hoistDuration, stagger: settings.stagger, mastSpacing: settings.mastSpacing, flagWidth: settings.flagWidth, flagHeight: settings.flagHeight, meshResolution: settings.meshResolution, windStrength: settings.windStrength, windStartPercent: settings.windStartPercent, windDirection: settings.windDirection, windGustiness: settings.windGustiness, windTurbulence: settings.windTurbulence, 'pole.visible': settings.pole.visible, 'pole.heightScale': settings.pole.heightScale, 'pole.finialSize': settings.pole.finialSize, 'pole.gloss': settings.pole.gloss, 'pole.color': settings.pole.color, 'pole.thickness': settings.pole.thickness, 'pole.finialStyle': settings.pole.finialStyle, 'pole.finialColor': settings.pole.finialColor, 'lighting.sunAzimuth': settings.lighting.sunAzimuth, 'lighting.sunElevation': settings.lighting.sunElevation, 'lighting.sunIntensity': settings.lighting.sunIntensity, 'lighting.sunColor': settings.lighting.sunColor, 'lighting.shadowsEnabled': settings.lighting.shadowsEnabled, 'lighting.shadowSoftness': settings.lighting.shadowSoftness, 'lighting.shadowQuality': settings.lighting.shadowQuality, 'background.type': settings.background.type, 'background.color': settings.background.color, 'background.url': settings.background.url, 'cloth.selfCollision': cloth.selfCollision, 'cloth.collisionThickness': cloth.collisionThickness, 'cloth.collisionIterations': cloth.collisionIterations, 'flagMaterial.gloss': flagMaterial.gloss, 'flagMaterial.metalness': flagMaterial.metalness, 'flagMaterial.clearcoat': flagMaterial.clearcoat, 'flagMaterial.clearcoatGloss': flagMaterial.clearcoatGloss }; document.querySelectorAll<HTMLInputElement | HTMLSelectElement>('[data-setting]').forEach((input) => { const key = input.dataset.setting; if (!key || !(key in values) || document.activeElement === input) return; if (input instanceof HTMLInputElement && input.type === 'checkbox') input.checked = Boolean(values[key]); else input.value = String(values[key]); }); const warning = document.getElementById('collision-warning'); if (warning) { warning.textContent = cloth.selfCollision ? 'Self-collision enabled · may reduce FPS with high mesh or many flags.' : 'Self-collision is off.'; warning.classList.toggle('is-active', cloth.selfCollision); } }
function syncBackground(): void { const transparent = settings.background.type === 'transparent'; const color = settings.background.type === 'color'; const colorInput = document.querySelector<HTMLInputElement>('[data-setting="background.color"]'); const urlInput = document.querySelector<HTMLInputElement>('[data-setting="background.url"]'); if (colorInput) colorInput.disabled = !color; if (urlInput) urlInput.disabled = color || transparent; const file = document.getElementById('background-file') as HTMLInputElement | null; if (file) file.disabled = transparent; document.querySelector('[data-background-color]')?.classList.toggle('is-muted', !color); document.querySelector('[data-background-url]')?.classList.toggle('is-muted', color || transparent); document.querySelector('[data-background-upload]')?.classList.toggle('is-muted', transparent); }
function uiPayload(): UiSettingsPayload { return { ...cloneSettings(settings), cloth: { ...cloth }, flagMaterial: { ...flagMaterial } }; }
function bounded(value: unknown, fallback: number, min: number, max: number): number { const parsed = typeof value === 'number' ? value : Number(value); return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback; }
function normalizedUiFields(value: unknown): { cloth: ClothSettings; flagMaterial: FlagMaterialSettings } { const source = value && typeof value === 'object' ? value as Record<string, unknown> : {}; const rawCloth = source.cloth && typeof source.cloth === 'object' ? source.cloth as Record<string, unknown> : {}; const rawMaterial = source.flagMaterial && typeof source.flagMaterial === 'object' ? source.flagMaterial as Record<string, unknown> : {}; return { cloth: { selfCollision: typeof rawCloth.selfCollision === 'boolean' ? rawCloth.selfCollision : DEFAULT_CLOTH.selfCollision, collisionThickness: bounded(rawCloth.collisionThickness, DEFAULT_CLOTH.collisionThickness, .01, .2), collisionIterations: rawCloth.collisionIterations === 2 ? 2 : 1 }, flagMaterial: { gloss: bounded(rawMaterial.gloss, DEFAULT_FLAG_MATERIAL.gloss, 0, 1), metalness: bounded(rawMaterial.metalness, DEFAULT_FLAG_MATERIAL.metalness, 0, 1), clearcoat: bounded(rawMaterial.clearcoat, DEFAULT_FLAG_MATERIAL.clearcoat, 0, 1), clearcoatGloss: bounded(rawMaterial.clearcoatGloss, DEFAULT_FLAG_MATERIAL.clearcoatGloss, 0, 1) } }; }
function readUiFields(value: unknown): void { const parsed = normalizedUiFields(value); cloth = parsed.cloth; flagMaterial = parsed.flagMaterial; }
function wireEvents(): void {
  document.addEventListener('click', (event) => { const target = event.target as HTMLElement; const action = target.closest<HTMLElement>('[data-action]'); if (action && !(action instanceof HTMLButtonElement && action.disabled)) { const name = action.dataset.action; if (name === 'add-slot') addSlot(); if (name === 'remove-slot') removeSlot(action.dataset.slotId ?? ''); if (name === 'open-ceremony') openCeremony(); if (name === 'open-api') (document.getElementById('api-dialog') as HTMLDialogElement | null)?.showModal(); if (name === 'close-api') (document.getElementById('api-dialog') as HTMLDialogElement | null)?.close(); if (name === 'save-preset') savePreset(); if (name === 'load-preset') loadPreset(); if (name === 'delete-preset') deletePreset(); if (name === 'export') exportSettings(); if (name === 'hoist-up') hoist('up'); if (name === 'hoist-down') hoist('down'); if (name === 'remove-flag') removeFlag(action.dataset.flagId ?? ''); } const copy = target.closest<HTMLButtonElement>('.copy-api'); if (copy) { const raw = copy.dataset.copy ?? ''; const parts = raw.split(/\s+/); const endpoint = parts.slice(1).join(' '); const url = parts[0] === 'WS' ? `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}${endpoint}` : `${window.location.origin}${endpoint}`; void navigator.clipboard?.writeText(url); showFeedback('Endpoint copied to clipboard.', 'success'); } });
  document.addEventListener('input', (event) => { const target = event.target as HTMLInputElement | HTMLSelectElement; if (target.matches('[data-setting]')) updateSetting(target); else if (target.matches('[data-flag-name]')) { const flag = settings.customFlags.find((item) => item.id === target.dataset.flagName); if (flag) { flag.name = target.value.slice(0, 120); debouncePersist(`flag:${flag.id}`); } } });
  document.addEventListener('change', (event) => { const target = event.target as HTMLInputElement | HTMLSelectElement; if (target.matches('[data-flag-replace]')) { void replaceFlag(target as HTMLInputElement); return; } if (target.matches('[data-setting]')) { updateSetting(target); if (target.dataset.setting === 'background.type') syncBackground(); return; } if (target.dataset.slotField === 'rank') updateSlot(target, 'rank', Number(target.value)); if (target.dataset.slotField === 'xOffset') updateSlot(target, 'xOffset', Number(target.value)); if (target.dataset.slotField === 'countryCode') { const custom = settings.customFlags.find((item) => item.id === target.value); const builtIn = eventFlags.find((item) => item.id === target.value); if (custom) updateSlot(target, 'flagId', custom.id); else if (builtIn?.imageUrl) updateSlot(target, 'flagId', builtIn.id); else if (!builtIn) updateSlot(target, 'countryCode', target.value); renderSlots(); } });
  importInput.addEventListener('change', importSettings); backgroundInput.addEventListener('change', uploadBackground); flagInput.addEventListener('change', uploadFlag);
}
function updateSetting(input: HTMLInputElement | HTMLSelectElement): void { const key = input.dataset.setting; if (!key) return; const value: string | number | boolean = input instanceof HTMLInputElement && input.type === 'checkbox' ? input.checked : input instanceof HTMLInputElement && input.type === 'number' ? Number(input.value) : input.value; if (typeof value === 'number' && !Number.isFinite(value)) return; if (key.startsWith('pole.')) (settings.pole as unknown as Record<string, unknown>)[key.slice(5)] = value; else if (key.startsWith('lighting.')) (settings.lighting as unknown as Record<string, unknown>)[key.slice(9)] = value; else if (key.startsWith('background.')) (settings.background as unknown as Record<string, unknown>)[key.slice(11)] = value; else if (key.startsWith('cloth.')) (cloth as unknown as Record<string, unknown>)[key.slice(6)] = key === 'cloth.collisionIterations' ? (Number(value) === 2 ? 2 : 1) : value; else if (key.startsWith('flagMaterial.')) (flagMaterial as unknown as Record<string, unknown>)[key.slice(13)] = value; else (settings as unknown as Record<string, unknown>)[key] = value; settings = normalizeSettings(uiPayload()); syncInputs(); input instanceof HTMLInputElement && input.type === 'number' ? debouncePersist(`setting:${key}`) : persistAndBroadcast(); }
function updateSlot(input: HTMLInputElement | HTMLSelectElement, field: keyof CeremonySlot, value: string | number): void { const slot = settings.slots.find((item) => item.id === input.dataset.slotId); if (!slot) return; if (field === 'rank') slot.rank = Math.max(1, Math.min(3, Number(value))) as 1 | 2 | 3; if (field === 'countryCode') { slot.countryCode = String(value).slice(0, 2).toUpperCase(); delete slot.flagId; } if (field === 'flagId') slot.flagId = String(value); if (field === 'xOffset') slot.xOffset = Math.max(-30, Math.min(30, Number(value))); persistAndBroadcast(); }
function addSlot(): void { if (settings.slots.length >= MAX_SLOTS) return showFeedback(`Maximum ${MAX_SLOTS} masts allowed.`, 'warning'); const n = settings.slots.length + 1; settings.slots.push({ id: `slot-${Date.now()}`, rank: Math.min(3, n) as 1 | 2 | 3, countryCode: 'NL', xOffset: 0 }); renderSlots(); persistAndBroadcast(); }
function removeSlot(id: string): void { if (settings.slots.length <= MIN_SLOTS) return; settings.slots = settings.slots.filter((slot) => slot.id !== id); renderSlots(); persistAndBroadcast(); }
function removeFlag(id: string): void { settings.customFlags = settings.customFlags.filter((flag) => flag.id !== id); settings.slots.forEach((slot) => { if (slot.flagId === id) delete slot.flagId; }); renderAll(); persistAndBroadcast(); }
function hoist(direction: 'up' | 'down'): void { send({ type: 'hoist', direction }); showFeedback(direction === 'up' ? 'Raise command sent.' : 'Lower-all command sent.', 'success'); }
function persistAndBroadcast(): void { settings = normalizeSettings(uiPayload()); readUiFields(settings); const payload = uiPayload(); localStorage.setItem(STORAGE_KEY, JSON.stringify(payload)); if (!applyingRemote) send({ type: 'update', settings: payload as CeremonySettings }); showFeedback('Settings saved and sent live.', 'success', 1500); }
function debouncePersist(key: string): void { const current = debounceTimers.get(key); if (current !== undefined) window.clearTimeout(current); debounceTimers.set(key, window.setTimeout(() => { debounceTimers.delete(key); persistAndBroadcast(); }, 220)); }
function loadAutosave(): void { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const value = JSON.parse(raw) as unknown; readUiFields(value); settings = normalizeSettings(value); } } catch { localStorage.removeItem(STORAGE_KEY); } }
function readPresets(): Record<string, UiSettingsPayload> { try { const value = JSON.parse(localStorage.getItem(PRESETS_KEY) ?? '{}') as Record<string, unknown>; const defaultPayload = { ...cloneSettings(DEFAULT_SETTINGS), cloth: { ...DEFAULT_CLOTH }, flagMaterial: { ...DEFAULT_FLAG_MATERIAL } }; const saved = Object.fromEntries(Object.entries(value).filter(([name, item]) => name !== DEFAULT_PRESET_NAME && isSettingsShape(item)).map(([name, item]) => { const normalized = normalizeSettings(item); const fields = normalizedUiFields(item); return [name, { ...normalized, ...fields }]; })); return { [DEFAULT_PRESET_NAME]: defaultPayload, ...saved }; } catch { return { [DEFAULT_PRESET_NAME]: { ...cloneSettings(DEFAULT_SETTINGS), cloth: { ...DEFAULT_CLOTH }, flagMaterial: { ...DEFAULT_FLAG_MATERIAL } } }; } }
function renderPresetList(): void { const selected = presetList.value; const presets = readPresets(); presetList.innerHTML = '<option value="">Select preset…</option>' + Object.keys(presets).sort().map((name) => `<option value="${escape(name)}">${escape(name)}</option>`).join(''); if (presets[selected]) presetList.value = selected; }
function savePreset(): void { const name = presetName.value.trim(); if (!name) return showFeedback('Enter a preset name first.', 'warning'); if (name === DEFAULT_PRESET_NAME) return showFeedback('The built-in Default preset cannot be overwritten.', 'warning'); const presets = readPresets(); presets[name] = uiPayload(); localStorage.setItem(PRESETS_KEY, JSON.stringify(presets)); renderPresetList(); presetList.value = name; showFeedback('Preset saved.', 'success'); }
function loadPreset(): void { const preset = readPresets()[presetList.value]; if (!preset) return showFeedback('Select a preset to load.', 'warning'); readUiFields(preset); settings = normalizeSettings(preset); renderAll(); persistAndBroadcast(); }
function deletePreset(): void { const name = presetList.value; if (!name || name === DEFAULT_PRESET_NAME) return showFeedback('The built-in Default preset cannot be deleted.', 'warning'); const presets = readPresets(); delete presets[name]; localStorage.setItem(PRESETS_KEY, JSON.stringify(presets)); renderPresetList(); }
function exportSettings(): void { const href = URL.createObjectURL(new Blob([JSON.stringify({ format: 'flag-ceremony-settings', version: 4, settings: uiPayload() }, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = href; anchor.download = `flag-ceremony-settings-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(href); }
async function importSettings(): Promise<void> { const file = importInput.files?.[0]; importInput.value = ''; if (!file) return; try { const value = JSON.parse(await file.text()) as { settings?: unknown }; const candidate = value.settings ?? value; if (!isSettingsShape(candidate)) throw new Error('invalid'); readUiFields(candidate); settings = normalizeSettings(candidate); renderAll(); persistAndBroadcast(); } catch { showFeedback('Import failed: invalid settings JSON.', 'error'); } }
function openCeremony(): void { const popup = window.open('/', '_blank', 'noopener,noreferrer'); if (!popup) showFeedback('Unable to open output. Allow pop-ups for this page.', 'warning'); }
async function uploadBackground(): Promise<void> { const file = backgroundInput.files?.[0]; backgroundInput.value = ''; if (!file) return; try { const response = await fetch('/api/v1/background', { method: 'POST', headers: { 'Content-Type': file.type }, body: file }); const result = await response.json() as { url?: string; type?: 'image' | 'video'; error?: string }; if (!response.ok || !result.url || !result.type) throw new Error(result.error ?? `Upload failed (${response.status})`); settings.background = { ...settings.background, type: result.type, url: result.url }; backgroundName.textContent = file.name; renderAll(); persistAndBroadcast(); } catch (error) { showFeedback(error instanceof Error ? error.message : 'Background upload failed.', 'error'); } }
async function uploadFlag(): Promise<void> { const file = flagInput.files?.[0]; flagInput.value = ''; if (!file) return; try { const response = await fetch('/api/v1/flags', { method: 'POST', headers: { 'Content-Type': file.type, 'X-Flag-Name': flagName.value.trim() || file.name.replace(/\.[^.]+$/, '') }, body: file }); const result = await response.json() as { id?: string; name?: string; imageUrl?: string; error?: string }; if (!response.ok || !result.id || !result.imageUrl) throw new Error(result.error ?? 'Upload failed'); settings.customFlags.push({ id: result.id, name: result.name ?? result.id, imageUrl: result.imageUrl }); flagFileName.textContent = file.name; flagName.value = ''; renderAll(); persistAndBroadcast(); } catch (error) { showFeedback(error instanceof Error ? error.message : 'Flag upload failed.', 'error'); } }
async function replaceFlag(input: HTMLInputElement): Promise<void> { const id = input.dataset.flagReplace; const file = input.files?.[0]; input.value = ''; if (!id || !file) return; try { const response = await fetch(`/api/v1/flags/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': file.type }, body: file }); const result = await response.json() as { imageUrl?: string; error?: string }; if (!response.ok || !result.imageUrl) throw new Error(result.error ?? 'Replace failed'); const flag = settings.customFlags.find((item) => item.id === id); if (flag) flag.imageUrl = result.imageUrl; renderAll(); persistAndBroadcast(); } catch (error) { showFeedback(error instanceof Error ? error.message : 'Replace failed.', 'error'); } }
function connect(): void { if (socket && (socket.readyState === WebSocket.OPEN || socket.readyState === WebSocket.CONNECTING)) return; updateStatus('connecting'); const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'; socket = new WebSocket(`${protocol}//${window.location.host}/ws`); socket.addEventListener('open', () => { updateStatus('connected'); send({ type: 'hello', role: 'control' }); }); socket.addEventListener('message', (event) => { try { const message = JSON.parse(String(event.data)) as ServerMessage; if (message.type !== 'state' && message.type !== 'executed') return; if (message.type === 'state' && message.state.revision === 0 && hadAutosave) { if (!autosaveBootstrapSent) { autosaveBootstrapSent = true; send({ type: 'update', settings: uiPayload() }); showFeedback('Restoring local settings to the server.', 'info'); } return; } applyingRemote = true; readUiFields(message.state.settings); settings = normalizeSettings(message.state.settings); localStorage.setItem(STORAGE_KEY, JSON.stringify(uiPayload())); renderAll(); applyingRemote = false; } catch { showFeedback('Invalid server message.', 'error'); } }); socket.addEventListener('close', () => { updateStatus('offline'); reconnectTimer = window.setTimeout(() => { reconnectTimer = undefined; connect(); }, 2000); }); socket.addEventListener('error', () => updateStatus('offline')); }
function send(message: ClientMessage): void { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify(message)); }
function updateStatus(value: 'connecting' | 'connected' | 'offline'): void { status.dataset.state = value; const strip = status.closest<HTMLElement>('.action-strip'); if (strip) strip.dataset.state = value; const label = status.querySelector<HTMLElement>('.status-label'); if (label) label.textContent = value === 'connected' ? 'Connected' : value === 'connecting' ? 'Connecting…' : 'Offline'; }
function showFeedback(message: string, tone: 'success' | 'info' | 'warning' | 'error', duration = 3600): void { feedback.textContent = message; feedback.dataset.tone = tone; if (feedbackTimer) window.clearTimeout(feedbackTimer); feedbackTimer = window.setTimeout(() => { feedback.textContent = ''; feedback.removeAttribute('data-tone'); }, duration); }
function isSettingsShape(value: unknown): value is Partial<CeremonySettings> { if (!value || typeof value !== 'object') return false; const candidate = value as Partial<CeremonySettings>; return Array.isArray(candidate.slots) && typeof candidate.pole === 'object' && candidate.pole !== null && typeof candidate.background === 'object' && candidate.background !== null; }
